# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-configmap
data:
  k6: |
    import http from "k6/http";
    import { sleep } from "k6";

    export let options = {
      scenarios: {
        s1: {
          executor: 'constant-arrival-rate',
          rate: 5,
          timeUnit: '1s',
          duration: '1000m',
          preAllocatedVUs: 20,
          maxVUs: 100,
        },
      }
    };

    export default function() {
        const url = __ENV.BASE_URI;
        let headers = {'Content-Type': 'application/json'};
        let data = {"operationName":null,"variables":{},"query":"{\n  coffees {\n    id\n    name\n    image\n    price\n    __typename\n  }\n}\n"};
        let response = http.post(url, JSON.stringify(data), {headers: headers});
        sleep(0.1)
    };

---
apiVersion: v1
kind: Service
metadata:
  name: traffic
  labels:
    app: traffic
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: traffic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
  labels:
    app: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        service: traffic
        app: traffic
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "frontend:80"
    spec:
      volumes:
      - name: k6
        configMap:
          name: k6-configmap
          items:
          - key: k6
            path: script.js
      serviceAccountName: traffic
      containers:
      - name: traffic
        image: loadimpact/k6
        volumeMounts:
          - name: k6
            mountPath: /k6
            readOnly: true
        command:
          - k6
          - run
          - /k6/script.js
        env:
        - name: BASE_URI
          value: http://127.0.0.1:80/api
        - name: DURATION
          value: "600"
        - name: SHOW_PROGRESS
          value: "false"
